import Head from 'next/head'
import Image from 'next/image'
import Navbar from '../components/Navbar'
import Main from '../components/Main'
import About from '../components/About'
import Skills from '../components/Skills'
import Projects from '../components/Projects'
import Contact from '../components/Contact'
import Footer from '../components/Footer'

export default function Home() {
  return (
    <div className='bg-#5651e5'>
      <Head>
        <title>Mark Teodoro | Front-End Web Developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='pb-20 lg:pb-1 md:pb-1 bg-[#131628]'><Main/></div>
      <div className='pb-40 lg:pb-1 md:pb-1 bg-[#131628]'><About/></div>
      <div className='pt-60 pb-28 lg:pb-1 lg:pt-1 md:pt-1 md:pb-1 bg-[#131628]'><Skills/></div>
      <div className='pt-60 pb-16 lg:pb-1 lg:pt-1 md:pt-1 md:pb-1 bg-[#131628]'><Projects/></div>
      <Contact/>
      <div className='mt-40 pt-56 pb-16'><Footer/></div>
    </div>
  )
}
